### ISSUE TITLE
Ionic - Typescript

### ISSUE THREAD

**Issue by abarandica** [Kumulos/KumulosSdkCordova#1]
Do you have used this plugin with Ionic 2+ and typescript?

**Comment by cgwyllie** [comment]
Hi!

It is certainly possible to use this plugin with Ionic, you would just install it as any other cordova plugin and then create a `kumulosSdk.Client` instance as documented in the README. TypeScript should not affect integration, the library APIs would remain the same.

Hope this helps.

**Comment by cgwyllie** [comment]
We have released version 2.0.2 which adds a type definitions file. This makes integration with TypeScript projects smoother as you would not have to declare the `kumulosSdk` library to the TypeScript compiler.
